name: run on push shell
on: [push]
jobs:
  run-bash-command:
    runs-on: ubuntu-latest
    name: "hellow world"
    steps:
      - uses: actions/checkout@master
      - name: "echo msg"
        run: echo "hai kamal"
      - name: "print env"
        run: env
      - name: "print pwd"
        run: pwd
      - run: echo "pwd"
      - name:  "execute the bash script"
        run: bash run.sh
    
