name: run on push shell
on: [push]
jobs:
  run-bash-command:
    runs-on: ubuntu-latest
    name: "hellow world"
    steps:
      - uses: actions/checkout@master
      - name:  " image from  Docker file"
        run: docker build -t coderbyte:1.0  aws-s3/.
      - name: "run the containter"
        run: docker run coderbyte:1.0 
    
